version: "3.9"
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    volumes:
      - zookeeper:/bitnami/zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - spritdb
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "127.0.0.1:9092:9092"
    volumes:
      - kafka:/bitnami/kafka
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENERS: "INTERNAL://:9093,EXTERNAL://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "INTERNAL://kafka:9093,EXTERNAL://kafka-server:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"
    depends_on:
      - zookeeper
    networks:
      - spritdb
#  kafdrop:
#    image: obsidiandynamics/kafdrop
#    ports:
#      - "127.0.0.1:9000:9000"
#    environment:
#      KAFKA_BROKERCONNECT: kafka:9092
#      SERVER_SERVLET_CONTEXTPATH: "/"
#      JVM_OPTS: "-Xms32M -Xmx64M"
#    depends_on:
#      - zookeeper
#    networks:
#      - spritdb
networks:
  spritdb:
    name: spritdb-net
volumes:
  zookeeper:
  kafka: